/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session */
        get: operations["session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn */
        post: operations["turn_api_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/confirmations/{pending_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_confirmations__pending_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_api_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbox/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Visit */
        post: operations["add_visit_api_inbox__visit_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reminders */
        get: operations["reminders_api_reminders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Data */
        delete: operations["delete_data_api_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionState
         * @description Lifecycle of a proposed reminder.
         * @enum {string}
         */
        ActionState: "proposed" | "confirmed" | "executed" | "failed";
        /**
         * ChangeCard
         * @description How one subject's dimension changed, with before and after runs.
         */
        ChangeCard: {
            /** Subject */
            subject: string;
            dimension: components["schemas"]["Dimension"];
            change: components["schemas"]["ChangeType"];
            /** Before */
            before: components["schemas"]["SegmentCard"][];
            /** After */
            after: components["schemas"]["SegmentCard"][];
            /** Future Effective */
            future_effective: boolean;
            /** Temporary */
            temporary: boolean;
            /** End Not Captured */
            end_not_captured: boolean;
            /** Sources */
            sources: components["schemas"]["SourceInfo"][];
        };
        /**
         * ChangeType
         * @description How a dimension's schedule changed between two knowledge points.
         * @enum {string}
         */
        ChangeType: "added" | "removed" | "changed";
        /**
         * CommitKind
         * @description What a CareCommit describes.
         * @enum {string}
         */
        CommitKind: "medication_instruction" | "monitoring_instruction" | "appointment" | "procedure" | "test" | "follow_up" | "observation";
        /**
         * ConfirmRequest
         * @description A tap on a confirmation card.
         */
        ConfirmRequest: {
            /**
             * Answer
             * @enum {string}
             */
            answer: "yes" | "no";
        };
        /**
         * DataDeletedCard
         * @description The user's data was deleted.
         */
        DataDeletedCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "delete_my_data";
            data: components["schemas"]["DataDeletedResult"];
        };
        /**
         * DataDeletedResult
         * @description The user's partition was emptied.
         */
        DataDeletedResult: {
            /** Speech */
            speech: string;
        };
        /**
         * DateBasis
         * @description How a date was established from the source text.
         * @enum {string}
         */
        DateBasis: "explicit" | "relative" | "none";
        /**
         * Dimension
         * @description A comparable aspect of a care item: the unit of plans and diffs.
         * @enum {string}
         */
        Dimension: "action" | "dose" | "time_of_day" | "food_relation" | "days_of_week" | "scheduled_for" | "interval";
        /**
         * EntityMatch
         * @description How confidently an extracted subject maps to a known entity.
         * @enum {string}
         */
        EntityMatch: "matched" | "possible_match" | "new" | "ambiguous";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Connection status for the simulator header.
         */
        HealthResponse: {
            /** Addon Reachable */
            addon_reachable: boolean;
            /** Model Tools */
            model_tools: number;
            /** Orchestrator */
            orchestrator: string;
        };
        /**
         * ItemCard
         * @description One captured item awaiting the user's confirmation.
         */
        ItemCard: {
            /** Commit Id */
            commit_id: string;
            kind: components["schemas"]["CommitKind"];
            /** Subject */
            subject: string;
            /** Summary */
            summary: string;
            /** Temporary */
            temporary: boolean;
            source: components["schemas"]["SourceInfo"];
            signals: components["schemas"]["Signals"];
        };
        /**
         * ItemsAddedCard
         * @description Items just added to the care plan.
         */
        ItemsAddedCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "confirm_items";
            data: components["schemas"]["ItemsAddedResult"];
        };
        /**
         * ItemsAddedResult
         * @description The items this confirmation verified.
         */
        ItemsAddedResult: {
            /** Speech */
            speech: string;
            /** Commit Ids */
            commit_ids: string[];
        };
        /**
         * OpenQuestionsCard
         * @description Open clarification questions.
         */
        OpenQuestionsCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "open_questions";
            data: components["schemas"]["OpenQuestionsResult"];
        };
        /**
         * OpenQuestionsResult
         * @description Every open clarification question.
         */
        OpenQuestionsResult: {
            /** Speech */
            speech: string;
            /** Questions */
            questions: components["schemas"]["QuestionCard"][];
        };
        /**
         * PendingConfirmation
         * @description The app-only tool a host calls, with these arguments, after the user says yes.
         */
        PendingConfirmation: {
            /**
             * Tool
             * @enum {string}
             */
            tool: "confirm_items" | "confirm_reminder";
            /** Arguments */
            arguments: {
                [key: string]: string | string[];
            };
        };
        /**
         * PendingView
         * @description What the UI needs to offer a confirmation button.
         */
        PendingView: {
            /** Pending Id */
            pending_id: string;
            /**
             * Tool
             * @enum {string}
             */
            tool: "confirm_items" | "confirm_reminder";
        };
        /**
         * PlanDayCard
         * @description The plan on one day.
         */
        PlanDayCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "plan_for_day";
            data: components["schemas"]["PlanDayResult"];
        };
        /**
         * PlanDayResult
         * @description The plan on one day.
         */
        PlanDayResult: {
            /** Speech */
            speech: string;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Entries */
            entries: components["schemas"]["PlanEntryCard"][];
        };
        /**
         * PlanEntryCard
         * @description What the plan says about one subject's dimension on a day.
         */
        PlanEntryCard: {
            /** Subject */
            subject: string;
            dimension: components["schemas"]["Dimension"];
            /** Values */
            values: string[];
            /** Temporary */
            temporary: boolean;
            /** End Captured */
            end_captured: boolean;
            source: components["schemas"]["SourceInfo"];
        };
        /**
         * QuestionCard
         * @description An open clarification question and where its gap came from.
         */
        QuestionCard: {
            /** Issue Id */
            issue_id: string;
            /** Question */
            question: string;
            /** Subject */
            subject: string;
            source: components["schemas"]["SourceInfo"];
        };
        /**
         * ReminderCard
         * @description A proposed or stored reminder.
         */
        ReminderCard: {
            /** Action Id */
            action_id: string;
            /** Text */
            text: string;
            /**
             * Alarm At
             * Format: date-time
             */
            alarm_at: string;
            state: components["schemas"]["ActionState"];
            based_on: components["schemas"]["SourceInfo"] | null;
        };
        /**
         * ReminderListResult
         * @description Every stored reminder, soonest first.
         */
        ReminderListResult: {
            /** Speech */
            speech: string;
            /** Reminders */
            reminders: components["schemas"]["ReminderCard"][];
        };
        /**
         * ReminderProposalCard
         * @description A reminder awaiting confirmation.
         */
        ReminderProposalCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "propose_reminder";
            data: components["schemas"]["ReminderProposalResult"];
        };
        /**
         * ReminderProposalResult
         * @description A proposed reminder and the confirmation that stores it, if there was a topic.
         */
        ReminderProposalResult: {
            /** Speech */
            speech: string;
            reminder: components["schemas"]["ReminderCard"] | null;
            confirmation: components["schemas"]["PendingConfirmation"] | null;
        };
        /**
         * ReminderStoredCard
         * @description A reminder just stored.
         */
        ReminderStoredCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "confirm_reminder";
            data: components["schemas"]["ReminderStoredResult"];
        };
        /**
         * ReminderStoredResult
         * @description The reminder this confirmation stored.
         */
        ReminderStoredResult: {
            /** Speech */
            speech: string;
            reminder: components["schemas"]["ReminderCard"];
        };
        /**
         * Role
         * @description Care-team role the user assigns to a session at import.
         * @enum {string}
         */
        Role: "family_physician" | "specialist" | "pharmacist" | "nurse" | "other_clinician" | "self";
        /**
         * SegmentCard
         * @description A run of days with the same value; ``end`` is exclusive.
         */
        SegmentCard: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Values */
            values: string[];
            /** Temporary */
            temporary: boolean;
            /** End Captured */
            end_captured: boolean;
        };
        /**
         * SelfRating
         * @description The extractor's own rating. Internal only; never shown as a number.
         * @enum {string}
         */
        SelfRating: "low" | "medium" | "high";
        /**
         * SessionView
         * @description The per-launch token the web app sends on every other request.
         */
        SessionView: {
            /** Token */
            token: string;
        };
        /**
         * Signals
         * @description Categorical review signals shown instead of confidence numbers.
         */
        Signals: {
            /**
             * Evidence
             * @default verified
             * @constant
             */
            evidence: "verified";
            date: components["schemas"]["DateBasis"];
            entity: components["schemas"]["EntityMatch"];
            speaker: components["schemas"]["SpeakerBasis"];
            model: components["schemas"]["SelfRating"];
        };
        /**
         * SourceInfo
         * @description Where an item came from: who said it, when, and the exact words.
         */
        SourceInfo: {
            /** Clinician */
            clinician: string;
            role: components["schemas"]["Role"];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Quote */
            quote: string;
        };
        /**
         * SpeakerBasis
         * @description Where a commit's speaker role came from.
         * @enum {string}
         */
        SpeakerBasis: "session_label" | "content_inferred";
        /**
         * TurnRequest
         * @description One spoken or typed request.
         */
        TurnRequest: {
            /** Text */
            text: string;
        };
        /**
         * TurnResult
         * @description What the simulator says and shows after one turn.
         */
        TurnResult: {
            /** Speech */
            speech: string;
            /** Card */
            card?: (components["schemas"]["VisitUpdatesCard"] | components["schemas"]["WhatsChangedCard"] | components["schemas"]["PlanDayCard"] | components["schemas"]["OpenQuestionsCard"] | components["schemas"]["ReminderProposalCard"] | components["schemas"]["ItemsAddedCard"] | components["schemas"]["ReminderStoredCard"] | components["schemas"]["VisitAddedCard"] | components["schemas"]["DataDeletedCard"]) | null;
            pending?: components["schemas"]["PendingView"] | null;
            /**
             * Error
             * @default false
             */
            error: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisitAddedCard
         * @description A visit just added from the inbox.
         */
        VisitAddedCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "add_visit";
            data: components["schemas"]["VisitAddedResult"];
        };
        /**
         * VisitAddedResult
         * @description The visit added and what compiling it produced.
         */
        VisitAddedResult: {
            /** Speech */
            speech: string;
            visit: components["schemas"]["VisitCard"];
            /** Created */
            created: number;
            /** Rejected */
            rejected: number;
        };
        /**
         * VisitCard
         * @description One visit in the inbox.
         */
        VisitCard: {
            /** Visit Id */
            visit_id: string;
            /** Title */
            title: string;
            /** Clinician */
            clinician: string;
            role: components["schemas"]["Role"];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Added */
            added: boolean;
        };
        /**
         * VisitListResult
         * @description Every visit in the inbox.
         */
        VisitListResult: {
            /** Speech */
            speech: string;
            /** Visits */
            visits: components["schemas"]["VisitCard"][];
        };
        /**
         * VisitUpdatesCard
         * @description New items from a visit, awaiting confirmation.
         */
        VisitUpdatesCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "visit_updates";
            data: components["schemas"]["VisitUpdatesResult"];
        };
        /**
         * VisitUpdatesResult
         * @description New items from one visit, and the confirmation that adds them.
         */
        VisitUpdatesResult: {
            /** Speech */
            speech: string;
            /** Clinician */
            clinician: string | null;
            /** Visit Date */
            visit_date: string | null;
            /** Items */
            items: components["schemas"]["ItemCard"][];
            confirmation: components["schemas"]["PendingConfirmation"] | null;
        };
        /**
         * WhatsChangedCard
         * @description What changed since the last visit.
         */
        WhatsChangedCard: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "whats_changed";
            data: components["schemas"]["WhatsChangedResult"];
        };
        /**
         * WhatsChangedResult
         * @description The CareDiff since the last visit and the open-question count.
         */
        WhatsChangedResult: {
            /** Speech */
            speech: string;
            /** Changes */
            changes: components["schemas"]["ChangeCard"][];
            /** Open Questions */
            open_questions: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    session_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    turn_api_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_confirmations__pending_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pending_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inbox_api_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitListResult"];
                };
            };
        };
    };
    add_visit_api_inbox__visit_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reminders_api_reminders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderListResult"];
                };
            };
        };
    };
    delete_data_api_data_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
        };
    };
}
